In [38]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [40]:
train= pd.read_csv('C:/Users/DELL LAPTOP/Desktop/Financial Analysis/Python/Prac- python/datasets/train.csv')
test= pd.read_csv('C:/Users/DELL LAPTOP/Desktop/Financial Analysis/Python/Prac- python/datasets/test.csv')
sampleSubmission_original= pd.read_csv('C:/Users/DELL LAPTOP/Desktop/Financial Analysis/Python/Prac- python/datasets/sampleSubmission_original.csv')

In [41]:
train=train.set_index('id')
test= test.set_index('id')
sampleSubmission_original=sampleSubmission_original.set_index('id')

In [42]:
train=train.sample(frac=1)

In [43]:
train.target.value_counts()

Class_2    16122
Class_6    14135
Class_8     8464
Class_3     8004
Class_9     4955
Class_7     2839
Class_5     2739
Class_4     2691
Class_1     1929
Name: target, dtype: int64

In [44]:
train['target'] = train['target'].replace(
    ['Class_1','Class_2','Class_3', 'Class_4', 'Class_5', 'Class_6', 'Class_7', 'Class_8', 'Class_9'],
    [0, 1,2,3,4,5,6,7,8])

In [45]:
train.head(10)

feat_1  feat_2  feat_3  feat_4  feat_5  feat_6  feat_7  feat_8  feat_9  \
id                                                                              
48640       0       0       0       1       0       0       0       0       0   
46192       0       0       0       0       0       0       0       3       0   
43057       6       0       1       1       0       0       0       0       1   
59650       4       0       1       0       0       0       0       1       0   
56070       0       0       0       0       0       0       0       0       0   
38192       0       2      11       7       0       0       0       1       0   
33197       0       1      32       5       0       0       0       1       0   
36533       1       0       0       3       0       0       0       0       0   
15028       0       0       0       0       0       0       0       0       0   
25395       0       0       0       0       0       0       0       0       0   

       feat_10  ...  feat_85  feat_86  feat_87  feat_88  feat_89  feat_90  \
id              ...                                                         
48640        0  ...        0        0        0        0        0        0   
46192        0  ...        1        2        0        2        0        0   
43057        3  ...        0        2        0        0        0        0   
59650        4  ...        5       15        0        0        2        5   
56070        0  ...        0        0        0        0        1        9   
38192        1  ...        0        1        0        0        1        0   
33197        0  ...        0        0        0        0        0        0   
36533        0  ...        0        2        4        4        2        0   
15028        0  ...        0        0        0        7        1        0   
25395        0  ...       16        0        0        0        0        1   

       feat_91  feat_92  feat_93  target  
id                                        
48640        0        2        0       7  
46192        0        1        0       6  
43057        0        0        0       5  
59650        0        0        0       8  
56070        0        0        0       7  
38192        0        2        0       5  
33197        0        1        0       5  
36533        0        0        1       5  
15028        0        0        0       1  
25395        0        0        0       2  

[10 rows x 94 columns]

In [46]:
# Splitting train data into labels and Features
X = train.drop('target', axis=1)
y = train['target']


In [47]:
# Splitting train data into train and validation
from sklearn.model_selection import train_test_split
train_X, val_X, train_y, val_y = train_test_split(X,y, train_size= 0.8, random_state= 4 )

In [48]:
# Creating and training models
from sklearn.naive_bayes import GaussianNB
gb = GaussianNB()
gb.fit(train_X, train_y)

GaussianNB()

In [49]:
predict_y=gb.predict(val_X)

In [50]:
# MEtrics
from sklearn.metrics import classification_report, confusion_matrix
confusion_matrix(predict_y, val_y)


array([[ 112,    2,    1,    0,    1,   86,   27,  260,   33],
       [  17, 2094,  758,  197,   14,   30,   63,   27,   36],
       [   9,  313,  391,   21,    4,   42,   71,   43,   17],
       [  19,  372,  284,  254,    3,  159,   63,    7,   26],
       [  31,  341,  104,   47,  500,   34,   16,   28,   58],
       [  16,    1,    2,    6,    3, 2208,   16,   64,   19],
       [  29,   58,   70,   16,    2,  101,  293,  126,    6],
       [   9,   15,    8,    0,    0,   46,   13,  918,   10],
       [ 132,   14,    1,    5,    0,  127,   11,  217,  799]],
      dtype=int64)

In [51]:
print(classification_report(predict_y, val_y))

              precision    recall  f1-score   support

           0       0.30      0.21      0.25       522
           1       0.65      0.65      0.65      3236
           2       0.24      0.43      0.31       911
           3       0.47      0.21      0.29      1187
           4       0.95      0.43      0.59      1159
           5       0.78      0.95      0.85      2335
           6       0.51      0.42      0.46       701
           7       0.54      0.90      0.68      1019
           8       0.80      0.61      0.69      1306

    accuracy                           0.61     12376
   macro avg       0.58      0.53      0.53     12376
weighted avg       0.64      0.61      0.60     12376



In [52]:
#ensemble
#Fitting Decision Tree classifier to the training set  
from sklearn.ensemble import RandomForestClassifier  
classifier= RandomForestClassifier(n_estimators= 10, criterion="entropy")  
classifier.fit(train_X, train_y)  

RandomForestClassifier(criterion='entropy', n_estimators=10)

In [53]:
predict_val = classifier.predict(val_X)

In [54]:
predict_val

array([5, 7, 8, ..., 5, 0, 1], dtype=int64)

In [55]:
confusion_matrix(predict_val, val_y)

array([[ 152,    3,    5,    2,    1,   18,   15,   26,   33],
       [  11, 2797,  831,  235,   13,   41,   96,   32,   32],
       [   2,  330,  730,   91,    0,    5,   55,    7,    3],
       [   0,   42,   29,  188,    0,    4,   10,    1,    0],
       [   1,    4,    0,    5,  510,    2,    4,    1,    4],
       [  57,    6,    7,   15,    1, 2645,   72,   85,   45],
       [  18,   15,    9,   10,    2,   27,  265,   10,    6],
       [  64,    6,    6,    0,    0,   56,   45, 1507,   54],
       [  69,    7,    2,    0,    0,   35,   11,   21,  827]],
      dtype=int64)

In [56]:
print(classification_report(predict_val, val_y))

              precision    recall  f1-score   support

           0       0.41      0.60      0.48       255
           1       0.87      0.68      0.77      4088
           2       0.45      0.60      0.51      1223
           3       0.34      0.69      0.46       274
           4       0.97      0.96      0.96       531
           5       0.93      0.90      0.92      2933
           6       0.46      0.73      0.57       362
           7       0.89      0.87      0.88      1738
           8       0.82      0.85      0.84       972

    accuracy                           0.78     12376
   macro avg       0.68      0.76      0.71     12376
weighted avg       0.81      0.78      0.79     12376



In [57]:
# test data
# SampleSubmission
# Taking RandomForest

In [58]:
predict_test=classifier.predict(test)

In [59]:
ind=sampleSubmission_original.index
result = pd.DataFrame(predict_test , index=ind )

In [60]:
result[0] = result[0].replace([0, 1,2,3,4,5,6,7,8],
                             ['Class_1','Class_2','Class_3', 'Class_4', 'Class_5', 'Class_6', 'Class_7', 'Class_8', 'Class_9'])


In [61]:
result

0
id             
1       Class_4
2       Class_6
3       Class_6
4       Class_4
5       Class_8
...         ...
144364  Class_1
144365  Class_3
144366  Class_3
144367  Class_2
144368  Class_3

[144368 rows x 1 columns]

In [62]:
sampleSubmission = pd.get_dummies(result[0])

In [63]:
sampleSubmission

Class_1  Class_2  Class_3  Class_4  Class_5  Class_6  Class_7  \
id                                                                      
1             0        0        0        1        0        0        0   
2             0        0        0        0        0        1        0   
3             0        0        0        0        0        1        0   
4             0        0        0        1        0        0        0   
5             0        0        0        0        0        0        0   
...         ...      ...      ...      ...      ...      ...      ...   
144364        1        0        0        0        0        0        0   
144365        0        0        1        0        0        0        0   
144366        0        0        1        0        0        0        0   
144367        0        1        0        0        0        0        0   
144368        0        0        1        0        0        0        0   

        Class_8  Class_9  
id                        
1             0        0  
2             0        0  
3             0        0  
4             0        0  
5             1        0  
...         ...      ...  
144364        0        0  
144365        0        0  
144366        0        0  
144367        0        0  
144368        0        0  

[144368 rows x 9 columns]

In [65]:
sampleSubmission.to_csv('sampleSubmission.csv')